[build]
command = "npm run build"
publish = "out"

[build.environment]
NODE_VERSION = "18"

[site]
bucket = "./out"
entry-point = "workers-site"

[env.production]
name = "personal-website"
routes = ["/*"] 